# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(choices=[('ch', 'Churrascaria'), ('jp', 'Comida Japonesa'), ('mx', 'Comida Mexicana')], default='ch', max_length=60),
        ),
    ]
