# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180417_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
